### 로그인 성공 -> redirect:/
POST http://localhost:8080/api/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
  "username" : "dnwjd123",
  "password" : "dnwjd123"
}

### 로그인 실패 -> redirect:/login
POST http://localhost:8080/api/login
Content-Type: application/json
X-Requested-With: XMLHttpRequest

{
"username" : "dnwjd123",
"password" : "Invalid"
}